# Page settings
baseurl = "localhost:1313"
title = "She's My OT"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = "jess@shesmyot.com.au"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = ""
    home = "Home"
    services = "Services"
    work = "Work"
    testimonials = "Testimonials"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Logo"
    subtitle = 'Occupational Therapy'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Fees"
    description = "<b>Initial Assessment</b> - $195<br><b>Follow-up</b> - $130<br><b>Travel</b> - $7 per 15 minutes traveled<br><br><i>Cancellations received after 2pm the day prior to your appointment will be charged at 90% of the fee.</i> "
    url = "#"
    icon = "icon-credit-card"
    img = "img_7.jpg"

  # [[params.intro.item]]
  #   title = "Develop"
  #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #   url = "#"
  #   button = "Click Me"
  #   icon = "icon-emotsmile"
  #   img = "img_8.jpg"

  # [[params.intro.item]]
  #   title = "Launch"
  #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #   url = "#"
  #   button = "Why us?"
  #   icon = "icon-rocket"
  #   img = "img_10.jpg"

  # [params.intro.video]
  #   enable = true
  #   title = "Watch the video"
  #   icon = "icon-play2"
  #   url = "https://vimeo.com/channels/staffpicks/93951774"

  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "Providing person-centered, in-home Occupational Therapy services with ♥"

    [[params.services.item]]
      title = "Home Safety Assessments"
      description = "Your OT will complete an initial assessment and followup interventions to prevent falls, increase accessibility, and to promote and maintain your independence at home."
      icon = "icon-home"

    [[params.services.item]]
      title = "Adaptive Equipment"
      description = "After your initial assessment, recommedations may be made for equipment to enable you to keep living the life you wish to live.  Utilizing a range of equipment suppliers allows me to ensure you get the right piece of equipment for YOU."
      icon = "icon-puzzle"
    [[params.services.item]]
      title = "Home Modifications"
      description = "Feeling unsafe in the shower?  Can't get that walker up and over that door threshold?  There's a rail and ramp for that!  I can prescribe home modifications and refer to your local Home Assist, or a qualified mobility and access builder."
      icon = "icon-wrench"

      [[params.services.item]]
      title = "Lymphoedema Treatment and Management"
      description = "As a certified Lymphoedema Therapist, I can work with your GP to assist in the management of your Lymphoedema through the treatment protocol of manual lymphatic drainage, bandaging, and compression garment prescriptions."
      icon = "icon-drop"


  # Work section
  # [params.work]
  #   enable = true
  #   title = "Work"
  #   description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
  #   footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

  #   [[params.work.row]]
  #     img = "work_1.jpg"
  #     alt = "Image2"
  #     title = "Project 1"
  #     subtitle = "Branding"

  #   [[params.work.row]]
  #     img = "work_2.jpg"
  #     alt = "Image2"
  #     title = "Project 2"
  #     subtitle = "Design"

  #   [[params.work.row]]
  #     img = "work_3.jpg"
  #     alt = "Image3"
  #     title = "Project 3"
  #     subtitle = "Design"

  #   [[params.work.row]]
  #     img = "work_4.jpg"
  #     alt = "Image4"
  #     title = "Project 4"
  #     subtitle = "Design"

  #   [[params.work.row]]
  #     img = "work_5.jpg"
  #     alt = "Image5"
  #     title = "Project 5"
  #     subtitle = "Design"

  #   [[params.work.row]]
  #     img = "work_6.jpg"
  #     alt = "Image6"
  #     title = "Project 6"
  #     subtitle = "Design"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    





  # About section
  [params.about]
    enable = true
    title = "About"
    description = "There is nothing like staying at home for real comfort. --Jane Austen"

    [[params.about.item]]
      name = "Jessica Aya"
      position = "Occupational Therapist"
      description = "You're the best arouuuuuund - nothings ever gonna take you down!"
      img = "jess-circle.png"
      alt = "Jessica Aya"
      social = [
        # ["icon-twitter", "#"],
        # ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Years Experience"
      icon = "icon-briefcase"
      from = 0
      to = 15
      interval = 100
      speed = 1500

    [[params.counters.item]]
      description = "Cups of tea"
      icon = "icon-cup"
      from = 0
      to = 21900
      interval = 25
      speed = 15000

    [[params.counters.item]]
      description = "Happy Clients"
      icon = "icon-people"
      from = 0
      to = 200
      interval = 50
      speed = 3000

    [[params.counters.item]]
      description = "Warm Smiles"
      icon = "icon-emotsmile"
      from = 0
      to = 986499
      interval = 50
      speed = 7500

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-clock", 'Hours:  W-F, 9a-3p'],
        ["icon-phone", "+61 402 498 817"],
        ["icon-envelope", "jess@shesmyot.com.au"],
        ["icon-globe", '<a href="https://shesmyot.com.au/" target="_blank">shesmyot.com.au</a>'],
        ["icon-home", "P.O. Box 145, Samford Village, QLD 4520"]
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Shes My OT. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        # ["icon-twitter", "#twitter"],
        # ["icon-facebook", "#facebook"],
        # ["icon-youtube", "#youtube"]
      ]
