baseurl = "shesmyot.com.au"
languageCode = "en-us"
theme = "hugo-elate-theme"
title = "She's My OT"
[params]
author = ""
custom_css = ["css/custom1.css", "css/custom2.css"]
description = ""
email = "jess@shesmyot.com.au"
googleMapsApiKey = "AIzaSyDRyBNMdqcHvIhp_gtEkBOwsU5oBKVg3Wg"
[params.about]
description = "There is nothing like staying at home for real comfort. --Jane Austen"
enable = true
title = "About"
[[params.about.item]]
alt = "Jessica Aya"
description = "You're the best arouuuuuund - nothings ever gonna take you down!"
img = "jess-circle.png"
name = "Jessica Aya"
position = "Occupational Therapist"
social = [["icon-linkedin", "#"]]
[params.contact]
button = "Send message"
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
details = [["icon-clock", "Hours:  W-F, 9a-3p"], ["icon-phone", "+61 402 498 817"], ["icon-envelope", "jess@shesmyot.com.au"], ["icon-globe", "<a href=\"https://shesmyot.com.au/\" target=\"_blank\">shesmyot.com.au</a>"], ["icon-home", "P.O. Box 145, Samford Village, QLD 4520"]]
email = "Email"
enable = true
form = true
map = true
message = "Message"
name = "Name"
phone = "Phone"
title = "Get in touch"
[params.counters]
background = "full_image_1.jpg"
enable = true
title = "Stats"
[[params.counters.item]]
description = "Years Experience"
from = 0
icon = "icon-briefcase"
interval = 100
speed = 1500
to = 15
[[params.counters.item]]
description = "Cups of tea"
from = 0
icon = "icon-cup"
interval = 25
speed = 15000
to = 21900
[[params.counters.item]]
description = "Happy Clients"
from = 0
icon = "icon-people"
interval = 50
speed = 3000
to = 200
[[params.counters.item]]
description = "Warm Smiles"
from = 0
icon = "icon-emotsmile"
interval = 50
speed = 7500
to = 986499
[params.footer]
copyright = "&copy; Shes My OT. All Rights Reserved. <br>Created by <a href=\"http://freehtml5.co/\" target=\"_blank\">FREEHTML5.co</a> Images: <a href=\"http://pexels.com/\" target=\"_blank\">Pexels</a>, <a href=\"http://plmd.me/\" target=\"_blank\">plmd.me</a> <br>Hugo port by: <a href=\"https://github.com/saey55\" target=\"_blank\">saey55</a>"
enable = true
links = []
[params.hero]
subtitle = "Occupational Therapy"
title = "Logo"
[[params.intro.item]]
description = "<b>Initial Assessment</b> - $195<br><b>Follow-up</b> - $130<br><b>Travel</b> - $7 per 15 minutes traveled<br><br><i>Cancellations received after 2pm the day prior to your appointment will be charged at 90% of the fee.</i> "
icon = "icon-credit-card"
img = "img_7.jpg"
title = "Fees"
url = "#"
[params.navigation]
about = "About"
brand = ""
contact = "Contact"
home = "Home"
services = "Services"
testimonials = "Testimonials"
work = "Work"
[params.services]
description = "Providing person-centered, in-home Occupational Therapy services with ♥"
enable = true
title = "Services"
[[params.services.item]]
description = "Your OT will complete an initial assessment and followup interventions to prevent falls, increase accessibility, and to promote and maintain your independence at home."
icon = "icon-home"
title = "Home Safety Assessments"
[[params.services.item]]
description = "After your initial assessment, recommedations may be made for equipment to enable you to keep living the life you wish to live.  Utilizing a range of equipment suppliers allows me to ensure you get the right piece of equipment for YOU."
icon = "icon-puzzle"
title = "Adaptive Equipment"
[[params.services.item]]
description = "Feeling unsafe in the shower?  Can't get that walker up and over that door threshold?  There's a rail and ramp for that!  I can prescribe home modifications and refer to your local Home Assist, or a qualified mobility and access builder."
icon = "icon-wrench"
title = "Home Modifications"
[[params.services.item]]
description = "As a certified Lymphoedema Therapist, I can work with your GP to assist in the management of your Lymphoedema through the treatment protocol of manual lymphatic drainage, bandaging, and compression garment prescriptions."
icon = "icon-drop"
title = "Lymphoedema Treatment and Management"
[params.testimonials]
description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
enable = true
title = "Testimonials"
[[params.testimonials.item]]
alt = "Person1"
img = "person1.jpg"
person = "Jean Doe, CEO <a href=\"http://freehtml5.co/\" target=\"_blank\">FREEHTML5.co</a> <span class=\"subtext\">Creative Director</span>"
quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
[[params.testimonials.item]]
alt = "Person2"
img = "person2.jpg"
person = "John Doe, Senior UI <a href=\"http://freehtml5.co/\" target=\"_blank\">FREEHTML5.co</a> <span class=\"subtext\">Creative Director</span>"
quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.&rdquo;"
[[params.testimonials.item]]
alt = "Person3"
img = "person3.jpg"
person = "Chris Nash, Director <a href=\"http://freehtml5.co/\" target=\"_blank\">FREEHTML5.co</a> <span class=\"subtext\">Creative Director</span>"
quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
